In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv("/Users/afrojkhan/Downloads/Online_Retail.csv", encoding="ISO-8859-1")

In [36]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [37]:
df.shape

(541909, 8)

In [38]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [39]:
df=df.drop(columns=["CustomerID"])

In [47]:
df_clean=df[df["UnitPrice"]>0]

In [48]:
df_clean=df_clean[df_clean['Quantity']>0]

In [49]:
df_clean.shape

(530104, 7)

In [50]:
df_clean.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

In [53]:
df_clean.sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
174692,551843,20749,ASSORTED COLOUR MINI CASES,2,5/4/11 13:57,7.95,United Kingdom
232371,557316,22906,12 MESSAGE CARDS WITH ENVELOPES,2,6/19/11 16:04,1.65,United Kingdom
80515,543040,22625,RED KITCHEN SCALES,1,2/2/11 17:06,8.50,United Kingdom
473816,576837,22893,MINI CAKE STAND T-LIGHT HOLDER,1,11/16/11 15:16,0.83,United Kingdom
140161,548373,21084,SET/6 COLLAGE PAPER CUPS,4,3/30/11 16:34,0.83,United Kingdom
304750,563613,22625,RED KITCHEN SCALES,4,8/18/11 8:49,8.50,Israel
3032,536592,90192,JADE DROP EARRINGS W FILIGREE,1,12/1/10 17:06,5.09,United Kingdom
275987,561026,84992,72 SWEETHEART FAIRY CAKE CASES,4,7/24/11 10:49,0.55,United Kingdom
429476,573556,22382,LUNCH BAG SPACEBOY DESIGN,10,10/31/11 13:51,1.65,United Kingdom
333207,566188,23397,FOOT STOOL HOME SWEET HOME,2,9/9/11 13:14,9.95,United Kingdom
495897,578335,23373,VINTAGE CHRISTMAS PAPER GIFT BAG,10,11/24/11 9:06,0.82,United Kingdom
52299,540702,22348,TEA BAG PLATE RED RETROSPOT,12,1/11/11 9:58,0.85,United Kingdom
78321,542864,84596E,SMALL LICORICE DES PINK BOWL,8,2/1/11 12:03,1.25,United Kingdom
231205,557250,84686,BEACH HUT MIRROR,1,6/17/11 15:59,4.25,United Kingdom
298999,563076,23207,LUNCH BAG ALPHABET DESIGN,100,8/11/11 16:12,1.45,Netherlands
210188,555277,22161,HEART DECORATION RUSTIC HANGING,2,6/1/11 17:30,0.79,United Kingdom
516305,579885,21993,FLORAL FOLK STATIONERY SET,3,11/30/11 17:37,1.25,United Kingdom
195169,553703,23108,SET OF 10 LED DOLLY LIGHTS,2,5/18/11 14:57,6.25,United Kingdom
76945,542664,22957,SET 3 PAPER VINTAGE CHICK PAPER EGG,1,1/31/11 12:14,5.79,United Kingdom
204068,554629,21713,CITRONELLA CANDLE FLOWERPOT,12,5/25/11 11:34,2.10,United Kingdom

In [55]:
non_digits=df_clean[~df_clean['InvoiceNo'].astype(str).str.isdigit()]
non_digits

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
299982,A563185,B,Adjust bad debt,1,8/12/11 14:50,11062.06,United Kingdom

In [56]:
df_clean=df_clean[df_clean['InvoiceNo'].astype(str).str.isdigit()]

In [76]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country,Revenue,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom,15.30,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom,22.00,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom,20.34,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,France,10.20,2011-12-09,12:50:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,France,12.60,2011-12-09,12:50:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,France,16.60,2011-12-09,12:50:00
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,France,16.60,2011-12-09,12:50:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,France,14.85,2011-12-09,12:50:00

In [64]:
alphanumberic_stock=df_clean[df_clean['StockCode'].astype(str).str.contains('[a-zA-Z]',regex=True)]
print('unique alphanumeric stock codes:')
print(alphanumberic_stock['StockCode'].unique()[:20])

unique alphanumeric stock codes:
['85123A' '84406B' '84029G' '84029E' 'POST' '82494L' '85099C' '84997B'
 '84997C' '84519A' '85183B' '85071B' '37444A' '37444C' '84971S' '15056BL'
 '15056N' '85049A' '85099B' '35004C']

In [66]:
df_clean=df_clean[~df_clean['StockCode'].astype(str).str.isalpha()]

In [67]:
df_clean.shape

(527918, 7)

In [69]:
cleaned_online_retail = pd.write_csv("df_clean")

AttributeError: module 'pandas' has no attribute 'write_csv'

In [71]:
# Calculate total revenue for eah row
df_clean['Revenue']=df_clean['Quantity'] * df_clean['UnitPrice']

/var/folders/06/mwqs0zn12gj5vrhcxdh_kz9h0000gn/T/ipykernel_52803/1578742519.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Revenue']=df_clean['Quantity'] * df_clean['UnitPrice']

In [73]:
# convert invoicedate to date time format
df_clean['InvoiceDate']=pd.to_datetime(df_clean['InvoiceDate'])

# create a clean date column(dropping the time stamp)
df_clean['Date']=df_clean['InvoiceDate'].dt.date

/var/folders/06/mwqs0zn12gj5vrhcxdh_kz9h0000gn/T/ipykernel_52803/3043586152.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean['InvoiceDate']=pd.to_datetime(df_clean['InvoiceDate'])
/var/folders/06/mwqs0zn12gj5vrhcxdh_kz9h0000gn/T/ipykernel_52803/3043586152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['InvoiceDate']=pd.to_datetime(df_clean['InvoiceDate'])
/var/folders/06/mwqs0zn12gj5vrhcxdh_kz9h0000gn/T/ipykernel_52803/3043586152.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Date']=df_clean['InvoiceDate'].dt.date

In [75]:
# create a clean time column(dropping the date stamp)
df_clean['Time']=df_clean['InvoiceDate'].dt.time

/var/folders/06/mwqs0zn12gj5vrhcxdh_kz9h0000gn/T/ipykernel_52803/3622064188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Time']=df_clean['InvoiceDate'].dt.time

In [77]:
df_clean=df_clean.drop(columns=['InvoiceDate'])

In [78]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,Country,Revenue,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,United Kingdom,15.30,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,United Kingdom,20.34,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,United Kingdom,22.00,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,United Kingdom,20.34,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,United Kingdom,20.34,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,France,10.20,2011-12-09,12:50:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,France,12.60,2011-12-09,12:50:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,France,16.60,2011-12-09,12:50:00
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,France,16.60,2011-12-09,12:50:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,France,14.85,2011-12-09,12:50:00